function [Fuel_Input, Grain_Struct, Engine_Parameters, Ambient_Input, Simulation_Settings] = TWR_Input()

Fuel_Input.name = 'HTPB';
Fuel_Input.propellant_density = 1115;        	        %Grain density [kg/m^3]
Fuel_Input.filename_temperature_combustion_interp = 'InputFiles/Interpolants/ABS_tempComb.RPATinterp';       	        %Combustion temperature [K]
Fuel_Input.filename_kappa_interp = 'InputFiles/Interpolants/ABS_kappa.RPATinterp';                               %Heat Capacity Ratio [-]
Fuel_Input.filename_molar_mass_interp = 'InputFiles/Interpolants/ABS_molarMass.RPATinterp';                           %Molar mass of combustion products [g/mol]
Fuel_Input.burn_coefficient = 0.22;                     %Temperature coefficient [mm/s] HTPB- 0.38 ABS- 0.358 swirl1-0.22 swirl2- 0.895
Fuel_Input.burn_expo = 0.71;                             %Burn rate exponent [-], Gox is in g/(s*cm^2) HTPB- 0.198 ABS- 0.198 swirl1-0.71 swirl2- 0.3284
Fuel_Input.Marxman_model = false;

Fuel_Input.different_layer = false;                              %Layer on top with different chemical properties
Fuel_Input.different_layer_burn_coefficient = 0.45;
Fuel_Input.different_layer_burn_expo = 0.205;
Fuel_Input.different_layer_thickness = [0.0012,0.0403];
Fuel_Input.different_layer_filename_temperature_combustion_interp = 'InputFiles/Interpolants/ABS_tempComb.RPATinterp';       	        %Combustion temperature [K]
Fuel_Input.different_layer_filename_kappa_interp = 'InputFiles/Interpolants/ABS_kappa.RPATinterp';                               %Heat Capacity Ratio [-]
Fuel_Input.different_layer_filename_molar_mass_interp = 'InputFiles/Interpolants/ABS_molarMass.RPATinterp';

% Grain_Struct.burn_area = 'InputFiles/Interpolants/TWR_burnArea.RPATinterp';                  % Dane do interpolacji powierzchni spalania
% Grain_Struct.channel_area = 'InputFiles/Interpolants/TWR_channelArea.RPATinterp';            % Dane do interpolacji powierzchni przek
% Grain_Struct.moments_of_inertia = 'InputFiles/Interpolants/TWR_momentsOfInertia.RPATinterp'; % Dane do interpolacji momentów bezwaładności ziarna 

Grain_Struct.max_burned_thickness = 0.12;  % Maksymalna dopuszczalna grubość warstwy spalonej
Grain_Struct.fuel_initial_COM = 1;      % Początkowe położenie środka ciężkości ziarna
Grain_Struct.initial_volume=0.0000933;        % Początkowa objętość ziarna

grain_number = 1;
Grain_Struct(grain_number).x_grain_base_wrt_nozzle_inlet = 0.01;
Grain_Struct(grain_number).Grain_stl_filename = '/InputFiles/STL/grain_A2HRM_16_100.stl';
Grain_Struct(grain_number).Inhibition.top_inhibited = false;
Grain_Struct(grain_number).Inhibition.bottom_inhibited = false;
Grain_Struct(grain_number).Inhibition.outer_inhibited = true;
Grain_Struct(grain_number).Inhibition.inner_inhibited = false;
Grain_Struct(grain_number).geometry_type = 1;
Grain_Struct(grain_number).period_instances = 16;
Grain_Struct(grain_number).grain_reversed = false; 
Grain_Struct(grain_number).slice_height = 0.001;
Grain_Struct(grain_number).coordinate_frame_axes = [3,1,2];
Grain_Struct(grain_number).constant_cross_section = true;

%Combustion chamber input data
Engine_Parameters.Chamber_Input.volume = 0.0000933*2.5; 
Engine_Parameters.Chamber_Input.max_pressure = 7000000;                % Max pressure inside combustion chamber
Engine_Parameters.Chamber_Input.min_pressure = 100000;                 % The minimum pressure at which combustion takes place
Engine_Parameters.Chamber_Input.initial_pressure = 1000000;            % Initial chamber pressure - generated by the igniter
Engine_Parameters.Chamber_Input.crosssection_area = pi*0.019^2;

%Tank input data
Engine_Parameters.Tank_Oxidizer.volume = 0.002;                % Tank volume     
Engine_Parameters.Tank_Oxidizer.max_pressure=6000000;                % Maximum allowable pressure in the tank
Engine_Parameters.Tank_Oxidizer.mass_vapourized=0.003;             % Random initial value of the evaporated mass
Engine_Parameters.Tank_Oxidizer.filling_temperature = 283;           % Refueling temperature
Engine_Parameters.Tank_Oxidizer.length = 1.4;                      % Tank length
Engine_Parameters.Tank_Oxidizer.diameter = 0.160;                    % Internal diameter of the tank
Engine_Parameters.Tank_Oxidizer.max_liquid_level = 0.95;             % The maximum allowable liquid level in the tank
Engine_Parameters.Tank_Oxidizer.temperature = 300;                   % Initial temperature of the oxidizer
Engine_Parameters.Tank_Oxidizer.oxidizer_total_mass = 0.8;           % The initial mass oxidizes in the tank
Engine_Parameters.Tank_Oxidizer.oxidizer_initial_COM=0.648725;       % The initial position of the center of gravity of the oxidizer

%Power system input
Engine_Parameters.Feed_Input.type = 'Self-pressurizng';    % The type of power system used
Engine_Parameters.Feed_Input.discharge_coefficient = 0.7;    % Power loss factor
Engine_Parameters.Feed_Input.orifices_number = 15;         % Number of orrifices in the injection plate
Engine_Parameters.Feed_Input.orifices_diameter = 0.0006;   % The diameter of the holes in the injection plate
 
%Input of the oxidizer in the tank
Engine_Parameters.Tank_Oxidizer.name = 'N2O';                                % The name of the oxidant 
Engine_Parameters.Tank_Oxidizer.type = 'double-phase';                       % Type of oxidizer
Engine_Parameters.Tank_Oxidizer.critical_pressure = 7.251 * 10^6;            % Critical pressure
Engine_Parameters.Tank_Oxidizer.critical_temperature = 308;                  % Critical temperature
Engine_Parameters.Tank_Oxidizer.critical_compressibility_factor = 0.28;      % Critical compressibility factor
Engine_Parameters.Tank_Oxidizer.gamma = 1.3;                                 % The adiabatic exponent for N2O
Engine_Parameters.Tank_Oxidizer.properties = 'InputFiles/Interpolants/N2O.RPAToxidizer';

%Nozzle data

Engine_Parameters.Nozzle_Input.throat_diameter =  0.012;  %Diameter [m] of nozzle throat
Engine_Parameters.Nozzle_Input.efficiency = 1;  %Nozzle efficiency [-]

%Ambient data

Ambient_Input.pressure = 101325;                           %Ambient pressure[Pa]
Ambient_Input.temperature = 283.0;                      %Ambient temperature[K]

Simulation_Settings.time_step = 0.001;                %Time step for calculations [s]
Simulation_Settings.solver_type = 'euler';
Simulation_Settings.time_max = 60;                     %Simulation time [s]
Simulation_Settings.Booleans.enable_erosive_burning = false;
Simulation_Settings.Booleans.perform_visualisation = false;  %Boolean operator for performing visualisation
Simulation_Settings.Booleans.perform_nozzle_optimization = false;
Simulation_Settings.Booleans.enable_nozzle_erosion = false;                        %flag which enables nozzle erosion
Simulation_Settings.Booleans.thrust_pressure_term = true;
Simulation_Settings.Booleans.pressure_dependent_burn_coeffs = false;
Simulation_Settings.Booleans.draw_plots = true;
Simulation_Settings.Booleans.generate_output_all = true;                    %The big txt file
Simulation_Settings.Booleans.generate_rfs_input = true;
Simulation_Settings.Booleans.generate_output_short = true;                  %The file with average values, like the one Szymon sent (BOSSMAN.out).
Simulation_Settings.Booleans.load_grain_struct = false;                      %if false - read .stl; if true - read .mat Grain_Struct
Simulation_Settings.Booleans.hybrid_engine = true;
Simulation_Settings.Booleans.hybrid_more_accurate_dPdt_eqn = false;
Simulation_Settings.Booleans.perform_3D_visualisation = false;
Simulation_Settings.Booleans.Cd_optimization = false;
Simulation_Settings.grain_struct_path = 'InputFiles/Grains/TWR.mat';

Simulation_Settings.Plots_Settings.cross_section_visualisation = false;
Simulation_Settings.Plots_Settings.burn_area = true;
Simulation_Settings.Plots_Settings.burn_rate = true;
Simulation_Settings.Plots_Settings.volume = false;
Simulation_Settings.Plots_Settings.nozzle_mass_flow = false;
Simulation_Settings.Plots_Settings.produced_mass_flow = false;
Simulation_Settings.Plots_Settings.pressure = true;
Simulation_Settings.Plots_Settings.tank_pressure = true;
Simulation_Settings.Plots_Settings.tank_temperature = false;
Simulation_Settings.Plots_Settings.of_ratio = true;
Simulation_Settings.Plots_Settings.burned_thickness = true;
Simulation_Settings.Plots_Settings.burn_area = true;
Simulation_Settings.Plots_Settings.channel_area = false;
Simulation_Settings.Plots_Settings.total_mass_flow_rate = false;
Simulation_Settings.Plots_Settings.fuel_mass_flow_rate = true;
Simulation_Settings.Plots_Settings.oxidizer_mass_flow_rate = true;
Simulation_Settings.Plots_Settings.oxidizer_mass_flow_rate_HEM = false;
Simulation_Settings.Plots_Settings.oxidizer_mass_flow_rate_SPI = false;
Simulation_Settings.Plots_Settings.oxidizer_mass_flux = false;
Simulation_Settings.Plots_Settings.propellant_mass = false;
Simulation_Settings.Plots_Settings.fuel_mass = false;
Simulation_Settings.Plots_Settings.oxidizer_mass = true;
Simulation_Settings.Plots_Settings.oxidizer_mass_liquid = false;
Simulation_Settings.Plots_Settings.oxidizer_mass_vapour = false;
Simulation_Settings.Plots_Settings.oxidizer_mass_vapourized = false;
Simulation_Settings.Plots_Settings.exit_velocity = false;
Simulation_Settings.Plots_Settings.kappa = false;
Simulation_Settings.Plots_Settings.molar_mass = false;
Simulation_Settings.Plots_Settings.temperature_combustion = true;
Simulation_Settings.Plots_Settings.c_star = false;
Simulation_Settings.Plots_Settings.total_impulse = false;
Simulation_Settings.Plots_Settings.specific_impulse = false;
Simulation_Settings.Plots_Settings.rCM = false;
Simulation_Settings.Plots_Settings.Ixx = false;
Simulation_Settings.Plots_Settings.Iyy = false;
Simulation_Settings.Plots_Settings.pressure_drop = true;
Simulation_Settings.Plots_Settings.dV = false;
Simulation_Settings.Plots_Settings.dVdt = false;
Simulation_Settings.Plots_Settings.thrust = true;
Simulation_Settings.Plots_Settings.exit_velocity = false;
Simulation_Settings.Plots_Settings.inertia = false;
Simulation_Settings.Plots_Settings.live_thrust_plot = false;
Simulation_Settings.Plots_Settings.klemmung = false;
Simulation_Settings.Plots_Settings.exit_pressure = false;
Simulation_Settings.Plots_Settings.exit_pressure = false;
Simulation_Settings.Plots_Settings.exit_temperature = false;
Simulation_Settings.Plots_Settings.exit_velocity = false;
Simulation_Settings.Plots_Settings.exit_mach = false;
Simulation_Settings.Plots_Settings.throat_pressure = false;
Simulation_Settings.Plots_Settings.throat_temperature = false;
Simulation_Settings.Plots_Settings.throat_velocity = false;

Simulation_Settings.Visualisation_Settings.auto_range_colorbar = 0;    %Should auto range be performed on colorbar or not?
Simulation_Settings.Visualisation_Settings.video_speed = 1.0;              %Value greater than 0 controlling the speed of visualisation video, 1 is normal speed, >1 is faster
Simulation_Settings.Visualisation_Settings.control_frame_rate = 0;     %Frame rate for writing of video
Simulation_Settings.Visualisation_Settings.frame_rate = 5;
Simulation_Settings.Visualisation_Settings.max_velocity = 500;             %Maximum motor velocity attainable

Simulation_Settings.Optimization_Input.throat_tolerance = 0.0005;         %Tolerance of optimization[m]
Simulation_Settings.Optimization_Input.exit_tolerance = 0.0005;           %Tolerance of optimization[m]
Simulation_Settings.Optimization_Input.allowed_pressure = 35;           %Maximum working pressure [MPa]
Simulation_Settings.Optimization_Input.upper_bound = 0.0095;				  %2 * max(Grain_Struct.outer_radius) 
end